### ISSUE TITLE
Feature: delete orphans

### ISSUE THREAD

**Issue by calebsw83** [Lukas1818/docker-lgogdownloader#1]
in the container, there's a flag for commands. I would like to add the download command, and also "lgogdownloader --check-orphans |xargs -r rm" in order to remove any older versions of files. Is it possible to do this? I saw on the web, some people say to set the command to be: `bash -c "command1 && command 2" `but i cannot get it to execute properly. Any ideas? Thank you

**Comment by msrd0** [comment]
This docker container uses a custom init script that does not execute the command you give it but rather passes the arguments on to lgogdownloader. If you want to run a bash command, try manually overwriting the entrypoint so that you can run bash just like you tried to.

**Comment by LuckyTurtleDev** [comment]
> This docker container uses a custom init script that does not execute the command you give it but rather passes the arguments on to lgogdownloader. If you want to run a bash command, try manually overwriting the entrypoint so that you can run bash just like you tried to.

This solution does only delete old data at the container start. If you use schedule the container the old data will not be deleted, at every run.

**Comment by LuckyTurtleDev** [comment]
I will update this container in a few days and add a environment variable, to delete orphan files.

**Comment by calebsw83** [comment]
Hey Lukas, I noticed you updated the container a few days ago. Did that happen to include this new environment variable you mentioned here?

**Comment by LuckyTurtleDev** [comment]
Sorry I have forget about this.
The updates was trigger automatically (maybe the base image was updated).

**Comment by LuckyTurtleDev** [comment]
@calebsw83  I have implementation this now, but because of a dns issue with my local docker, I was not able to test it. I checkout this again soon.
https://gitlab.com/Lukas1818/docker-lgogdownloader/-/commit/7fda4f1a53fd156d1a723f2860604dca6642a2ba

**Comment by LuckyTurtleDev** [comment]
@calebsw83 I have implemented this feature now. Can you please test it with `registry.gitlab.com/lukas1818/docker-lgogdownloader:alpine`?
```yml
version: '3.3'
services:
    lgogdownloader:
        image: registry.gitlab.com/lukas1818/docker-lgogdownloader:alpine
        container_name: lgogdownloader
        environment:
            - GOG_EMAIL=
            - GOG_PASSWORD=
            - DELETE_ORPHANS=true
        volumes:
            - './data:/home/user/downloads'
        command: --help
        restart: unless-stopped
```
